server:
  port: 8761
  
management:
  security:
    enabled: false

spring:
  application:
    name: microservice-discovery-eureka-ha
  profiles:
    active: peer1

##配置Eureka Server登录验证
#security: 
#  basic:
#    enabled: true
#  user:
#   name: user
#    password: password123

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true ##表示是否将自己注册到Eureka Server, 默认为true
    fetchRegistry: true ##表示是否从Eureka Server获取注册信息, 默认为true
    serviceUrl:
      ##设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka;多个地址间可用,分割
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      #defaultZone: http://user:password123@localhost:8761/eureka/
---
spring:
  profiles: peer1
server:
  port: 8761
#eureka:
#  instance:
#    hostname: peer1

---
spring:
  profiles: peer2
server:
  port: 8762
#eureka:
#  instance:
#    hostname: peer2
